- name: "Validate sudoers"
  command: visudo -cf /etc/sudoers.d/{{ new_user }}

- name: "Validate sshd config"
  command: sshd -t

- name: "Restart ssh"
  service:
    name: ssh
    state: restarted

- name: "Restart fail2ban"
  service:
    name: fail2ban
    state: restarted